version: 2
updates:
- package-ecosystem: npm
  directory: "/src/rest-server"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - abuccts
  - sunqinzheng
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: "@kubernetes/client-node"
    versions:
    - 0.14.0
    - 0.14.1
    - 0.14.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: nock
    versions:
    - 13.0.10
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
- package-ecosystem: npm
  directory: "/src/webportal"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - abuccts
  - sunqinzheng
  ignore:
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: react
    versions:
    - 17.0.1
- package-ecosystem: npm
  directory: "/contrib"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - abuccts
  - sunqinzheng
